{% set name = "libctl" %}
{% set version = "4.3.0" %}
{% set sha256 = "c0ff5e0a3d81ed70240181552fe2c2381ed7928ea138115dcfa196e7310de674" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/stevengj/{{ name }}/releases/download/v{{version}}/{{ name }}-{{version}}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}
  host:
  run:

test:
  commands:
    - test -f ${PREFIX}/lib/libctlgeom${SHLIB_EXT}

about:
  home: http:/github.com/stevengj/libctl
  license: GPL-2.0
  license_file: COPYING
  summary:  A Guile-based library for supporting flexible control files in scientific simulations
  doc_url: http://libctl.readthedocs.io
  dev_url: https://github.com/stevengj/libctl

extra:
  recipe-maintainers:
    - ChristopherHogan
    - oskooi
